site_name: Repath Studio
site_description: Vector Graphics Editor
site_author: Konstantinos Kaloutas
site_url: https://repath.studio/
copyright: 2026 © Repath Studio

repo_url: https://github.com/repath-studio/repath-studio
repo_name: repath-studio

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - announce.dismiss
  - navigation.instant
  - navigation.footer
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
  palette:
    - scheme: default
      primary: pink-700
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font: false

nav:
  - Home: index.md
  - Get Started:
    - get-started/download.md
    - get-started/history-tree.md
    - get-started/interactive-shell.md
    - get-started/smil-animations.md
    - Powered by SVG: get-started/powered-by-svg.md
  - Contribute:
    - Develop: contribute/contributing.md
    - Code of Conduct: contribute/CODE_OF_CONDUCT.md
    - LLMs: contribute/LLM_POLICY.md
    - CLA: contribute/CLA.md
  - Roadmap:
    - Milestones: roadmap/milestones.md
    - roadmap/changelog.md
  - Policies:
    - Privacy: policies/privacy.md
    - Security: policies/security.md
    - License: policies/license.md
  - News:
    - news/index.md

extra:
  generator: false
  social:
  - icon: fontawesome/solid/at
    link: mailto:contact@repath.studio
    name: Email us
  - icon: fontawesome/brands/product-hunt
    link: https://www.producthunt.com/products/repath-studio
    name: Find us on Product Hunt
  - icon: fontawesome/brands/discord
    link: https://discord.gg/yzjY6W6ame
    name: Join our Discord
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/repath.studio/
    name: Follow us on Instagram
  - icon: fontawesome/brands/github
    link: https://github.com/repath-studio/repath-studio
    name: Star us on GitHub

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - blog:
      blog_dir: news
  - git-revision-date-localized:
      exclude:
        - get-started/*
        - news/*
        - contribute/*
        - roadmap/*
        - index.md
  - social:
      cards_layout_options:
        font_family: Sora
        background_color: "#97124c"
